package com.oz.demojar.dao;

import com.oz.demojar.model.Order;
import com.oz.demojar.mysqlDatasource.OrderRepository;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Repository;

import java.util.*;
@Slf4j
@Primary
@Repository("orders")
class OrderDaoImpl implements OrderDao {

    @Autowired // This means to get the bean called CountryDataSource Which is auto-generated by Spring, we will use it to handle the data
    private transient OrderRepository orderRepository;

    public Order addOrder(String message) {

        try {
            Order orderObj = new Order(0L,message);
            return orderRepository.save(orderObj);
        } catch (Exception e) {
            log.error("ERROR: " + e.getMessage());
            e.getStackTrace();
            return null;
        }

    }

    public List<Order> selectAllOrders() {
        return orderRepository.findAll();
    }

    public Optional<Order> getOrderById(Long id) {
        return Optional.of(orderRepository.getById(id));
    }

    public void save(Order order) {
        orderRepository.save(order);
    }


}

