package com.oz.demojar.dao;

import com.oz.demojar.model.Country;
import com.oz.demojar.model.Passport;
import com.oz.demojar.model.Person;
import com.oz.demojar.mysqlDatasource.CountryRepository;
import com.oz.demojar.mysqlDatasource.PassportRepository;
import com.oz.demojar.mysqlDatasource.PersonRepository;

import org.hibernate.annotations.OrderBy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Primary;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Repository;
import org.springframework.validation.FieldError;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

@Primary
@Repository("person")
class PersonDaoImpl implements PersonDao {

    @Autowired // This means to get the bean called PersonRepository Which is auto-generated by Spring
    private transient PersonRepository personRepository;
    @Autowired
    private transient CountryRepository countryRepository;
    @Autowired
    private transient PassportRepository passportRepository;

    @PersistenceContext
    private EntityManager em;

    @Override
    public Person addPerson(String firstName, String lastName, Country country, String position, Integer age, Integer boss) {

//        if(country.getId() != null) {
//            c = countryRepository.getById(country.getId());
//        } else if (country.getName() != null) {
//            c = countryRepository.findByName(country.getName());
//        } else {
//            c = countryRepository.getById(19L);
//        }

        try {
            Person person = new Person(firstName, lastName, country, position, age, boss);
            Person newPerson = personRepository.save(person);
            System.out.println("PersonDaoImpl: "+newPerson);
            return newPerson;
        } catch (ConstraintViolationException e) {
            Set<ConstraintViolation<?>> errors;
            errors = e.getConstraintViolations();
            errors.forEach(error -> {
                String fieldName = ((FieldError) error).getField();
                String errorMessage = error.getMessage();
                System.out.println("field: " + fieldName + " msg: " + errorMessage);
            });
            return null;
        } catch (Exception e) {
            System.out.println("ERROR: " + e.getMessage());
            e.getStackTrace();
            return null;
        }

    }

    @Override
    public List<Person> selectAllPeople() {
        List<Person> persons = personRepository.findAll(Sort.by(Sort.Direction.DESC, "id"));
        Query query = em.createQuery("From Person");
        //List<Person> persons = query.getResultList();
        //Collections.sort(persons, Comparator.comparing(p -> (p.getLastName() == null) ? "" : p.getLastName().toLowerCase()));
        //return persons;

        // sorted without lower case
        //return  personDAO.findAll().stream().sorted(Comparator.comparing(Person::getLastName)).collect(Collectors.toList());

//
//        int n = 0;
//        List<Integer> rangeList = new ArrayList<>();
//        List<Integer> range= IntStream.range(10,n + 1)
//                .filter(i -> i % 2 > 0)
//                .boxed()
//                .collect(Collectors.toList());
//
//        rangeList.addAll(range);
//
//        System.out.println("rangeList:" + rangeList);
//
//        List<Integer> IntList = IntStream.range(1,n + 1)
//                .filter(i -> i % 3 == 0)
//                .boxed()
//                .collect(Collectors.toList());
//
//        System.out.println("IntList:" + IntList);
//
//        List<String> numbers = Arrays.asList("1", "2", "3", "4", "5", "6");
//        System.out.println("original list: " + numbers);
//
//        List<Integer> even = numbers.stream()
//                .map(s -> Integer.valueOf(s))
//                .filter(number -> number % 2 == 0)
//                .collect(Collectors.toList());
//
//        System.out.println("processed list, only even numbers: " + even);

        return persons;

    }

    @Override
    public int deletePersonById(Long id) {
        Optional<Person> person = getPersonById(id);
        if (person.isPresent()) {
            personRepository.delete(person.get());
            return 0;
        } else {
            return 1;
        }
    }

    public boolean updatePersonByIdShort(Long id, Person person) {
        Object p = personRepository.updateShortById(person.getLastName(), person.getFirstName(), id);
        System.out.println(p.toString());
        return (p.getClass() == Person.class);
    }

    @Override
    public Person updatePersonById(Long id, Person person) {
        Passport pass = null;
        Passport newPass;
        Country country = person.getCountry();
        System.out.println(person);
        Person oldPerson = personRepository.getById(id);

        if(person.getPassport() != null) {
            pass = passportRepository.getById(person.getPassport().getId());
            pass.setCountry(country);
            person.setPassport(pass);
        } else {
            person.setPassport(null);
        }
        person.setId(0L);
        System.out.println(oldPerson);
        if(!oldPerson.isValid()) { return null; }
        else {
            if((oldPerson.getCountry() != null && person.getCountry() != null ) &&
               (person.getCountry().getId() != null && oldPerson.getCountry().getId() != null) &&
               !(person.getCountry().getId().equals(oldPerson.getCountry().getId()))
            ) {
                person.setCountry(countryRepository.getById(person.getCountry().getId()));
                country = person.getCountry();
            }

            if((oldPerson.getPassport() != null && person.getPassport() != null ) &&
                    (person.getPassport().getId() != null && oldPerson.getPassport().getId() != null) &&
                    !(person.getPassport().getId().equals(oldPerson.getPassport().getId()))
            ) {
                pass = passportRepository.getById(person.getPassport().getId());
                if (!pass.getCountry().getId().equals(person.getCountry().getId())) {
                    pass.setCountry(person.getCountry());
                    Passport pas = passportRepository.save(pass);
                    System.out.println(pas);
                }
                person.setPassport(passportRepository.getById(person.getPassport().getId()));
            }

            if(person.getLastName()  == null) person.setLastName(oldPerson.getLastName());
            if(person.getFirstName() == null) person.setFirstName(oldPerson.getFirstName());
            if(person.getCountry()   == null) person.setCountry(oldPerson.getCountry());
            if(person.getPassport()  == null) person.setPassport(oldPerson.getPassport());

            personRepository.delete(oldPerson);
        }

        Person p = personRepository.save(person);
        if (pass != null) {
            newPass = setPersonToPassport(pass, p);
            System.out.println(newPass);
        }

        return p;
    }

    @Override
    public Optional<Person> getPersonById(Long id) {
        Optional<Person> personOpt = personRepository.findById(id);
        return personOpt;
    }

    @Override
    public void addPersonToCountry(Person p, Country c) {
        p.setCountry(c);
        personRepository.save(p);
    }

    public Person setPassportToPerson(Passport passport, Person person) {
        person.setPassport(passport);
        return personRepository.save(person);
    }

    public Passport setPersonToPassport(Passport passport, Person person) {
        passport.setPerson(person);
        return passportRepository.save(passport);
    }

    public Collection<Person> findAllAnns() {
        return personRepository.findAllAnns();
    }

    public Collection<Person> findPersonsWithPassportsByCountry(Long country_id) {
        System.out.println("cid :"+country_id);
        return personRepository.findPersonsWithPassportsByCountry(country_id);
    }

    public long findLastId() {
        return personRepository.findLastId();
    }

    public static Person deserialize(String fileName) throws Exception {
        FileInputStream file = new FileInputStream(fileName);
        ObjectInputStream in = new ObjectInputStream(file);
        Person book = (Person) in.readObject();
        in.close();
        file.close();
        return book;
    }

}

