apiVersion: v1
kind: Pod
metadata:
  name: items-backend
spec:
  containers:
    - image: docker.io/plazolas/items-backend
      name: items-backend
      imagePullPolicy: Always
      resources: {}
      env:
        - name: APP_DB_PASSWORD
          ValueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
      ports:
        - containerPort: 8080
