apiVersion: v1
kind: Service
metadata:
  name: items-backend-srvc
  labels:
    run: items-backend
spec:
  ports:
  - port: 8077
    protocol: TCP
    targetPort: 8077
  selector:
    app: items-backend
  type: LoadBalancer
